add_newline = false

format = "$directory$git_branch$all$character"


[hostname]
disabled = true

[username]
disabled = true
style_user = "bold dimmed blue"
show_always = false


[battery]
disabled = true
# full_symbol = ":battery: "
# charging_symbol = ":zap:️ "
# discharging_symbol = ":skull: "

# [package]
# disabled = true

# [character]
# disabled = true

# [cmd_duration]
# disabled = true

[gcloud]
disabled = true

[aws]
disabled = true
format = '[$symbol($profile )]($style)'

[character]
success_symbol = "[❯](bold white)"
error_symbol = "[❯](bold red)"

[cmd_duration]
disabled = false

[directory]
truncation_length = 1
format = "[$path]($style)[$lock_symbol]($lock_style) "
# style = "bold yellow"

[git_branch]
disabled = false
format = "[$symbol$branch]($style) "
symbol = ""
style = "bold white"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
style = "white"

[package]
disabled = true

[ruby]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[kubernetes]
format = '[⎈ $context( \($namespace\))](blue) '
disabled = false

[kubernetes.context_aliases]
"eks_(?P<cluster>[\\w-]+)" = "$cluster"
"arn:aws:eks:.+:.+:cluster/(?P<cluster>[\\w-]+)" = "$cluster"
"services.yuma_fuu-terraform.user@(?P<cluster>[\\w-]+).ap-northeast-1.eksctl.io" = "$cluster"

[conda]
disabled = true

# [helm]
# disabled = false
# format = "via [⚙ $version](bold white) "

