version: '3'

tasks:
  stylua:
    desc: Format lua
    cmds:
      - stylua -g '*.lua' -- .
    silent: true
  shellcheck:
    desc: Lint shell scripts
    cmds:
      - shellcheck zsh/*.zsh .zshrc
    silent: true
  shellcheck-fix:
    desc: Lint shell scripts (Fix)
    cmds:
      - shellcheck -f diff zsh/*.zsh .zshrc > /tmp/shellcheck.diff
      - patch -p1 < /tmp/shellcheck.diff
    silent: true

include:
  - karabiner/Taskfile.yaml
