version: '3'

tasks:
  stylua:
    desc: Format lua
    cmds:
      - stylua -g '*.lua' -- .
    silent: true
  shellcheck:
    desc: Lint shell scripts
    cmds:
      - shellcheck -f diff zsh/*.zsh zshrc > /tmp/shellcheck.diff
      - patch -p1 < /tmp/shellcheck.diff
    silent: true
