#!/usr/bin/env -S deno run -A

import $ from "jsr:@david/dax"

const envs = {
  dev: {
    url: "postgres://knowledgework-dev:knowledgework-dev@localhost:5432/knowledgework-dev",
    proxy: "knowledgework-dev:us-west1:knowledgework-dev-db-instance-1",
  }
}

let env = Deno.args[0];
if (!env) {
  console.log('[INFO] use default environment `dev`')
  env = `dev`
  // console.log(`lazysql[ERROR] env is required.`)
  // Deno.exit(1)
}

const setting = envs[env]

if (!setting) {
  console.log(`[ERROR] ${env} is not supported`)
  Deno.exit(1)
}

const { url, proxy } = setting

await Promise.all([
  $`cloud-sql-proxy ${proxy}`,
  $.withRetries({
    count: 5,
    delay: "2s",
    action: async () => {
      await $`lazysql ${url}?sslmode=disable`
    },
  }),
])
