#!/usr/bin/env -S deno run -A

import $ from "jsr:@david/dax";
import { parse, stringify } from "jsr:@std/toml";

const list = []
const ghqlist = await $`ghq list`.lines()

console.log({ list })

for (const line of list) {
  console.log({ line })
}

const costom = await $`ghq list`.lines()
