#!/usr/bin/env bash
if [ $# -eq 0 ]; then
  echo "Usage: gp <commit-message>"
  exit 1
fi

git add . &&
git commit -m "$*" &&
git push origin $( git branch | grep "*" | sed -e "s/^\*\s*//g" ) &&
gh pr view --web
