fzf:
  preview: "eza --tree --icons -L 2 $(_ghq-fzf fullpath {})"
ghq:
  showFullpath: false
  nested:
    - root: github.com/yumafuu/bite-poc-cli
      dirs:
        - core
external:
  - "~/dotfiles"
  - "~/dotfiles/nvim"
  - "~/dotfiles/karabiner"
  - "~/Downloads"
