fzf:
  preview: "eza --tree --icons -L 2 $(_ghq-fzf fullpath {})"
ghq:
  showFullpath: false
  nested:
    - root: github.com/knowledge-work/knowledgework
      dirs:
        - z-playground/yuma
        - z-playground/yuma/sharepoint-api
  exclude:
    - github.com/knowledge-work/og-generator
    - github.com/knowledge-work/experimental
external:
  - "~/dotfiles"
  - "~/dotfiles/nvim"
  - "~/dotfiles/karabiner"
  - "~/Downloads"
  - "~/junk"
