shell = "zsh"

[plugins]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

[plugins.pure]
github = 'sindresorhus/pure'
use = ["async.zsh", "pure.zsh"]

[plugins.local]
local = '~/dotfiles/zsh'
