export const Vivaldi = "com.vivaldi.Vivaldi"
export const Discord = "com.hnc.Discord"
export const Slack = "com.tinyspeck.slackmacgap"
export const ReflectApp = "app.reflect.ReflectDesktop"
export const Spark = "com.readdle.SparkDesktop"
export const Wezterm = "com.github.wez.wezterm"
